# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 624b4206d080382ddc0a80b5a6f531753ab7f7e04e427035691d228a4dc8cc0ad2e46d07c15e7707a31bda0cf351acc352e90d0e866bf6958f13d10aba914add

test:
  secret_key_base: a827f137437f148794c2743df473a91d49525151f693fdfcb9709a91ab4f7dfa89b05be302036007f64653e0b8388dbbcf66c547f4f1e44b0184541124a09cfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
